### ISSUE TITLE
Cannot find module 'event-kit'

### ISSUE THREAD

**Issue by joelburget** [freebroccolo/atom-language-redprl#9]
On a fresh Atom install, this is the first package I tried to install following the instructions in install.md.

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.5
**Thrown From**: [language-redprl](https://github.com/RedPRL/atom-language-redprl) package, v0.0.0

### Stack Trace

Failed to load the language-redprl package

```
At Cannot find module 'event-kit'

Error: Cannot find module 'event-kit'
    at Module._resolveFilename (module.js:338:15)
    at Function.Module._resolveFilename (/Users/joel/Downloads/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (/Users/joel/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/joel/github/atom-language-redprl/lib/redprl.js:5:34)
    at Module._compile (/Users/joel/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Users/joel/Downloads/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/Users/joel/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/joel/github/atom-language-redprl/lib/main.js:7:15)
    at Module._compile (/Users/joel/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Users/joel/Downloads/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/Users/joel/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/Users/joel/Downloads/Atom.app/Contents/Resources/app.asar/src/package.js:715:27)
    at /Users/joel/Downloads/Atom.app/Contents/Resources/app.asar/src/package.js:117:28
    at Package.module.exports.Package.measure (/Users/joel/Downloads/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at Package.module.exports.Package.load (/Users/joel/Downloads/Atom.app/Contents/Resources/app.asar/src/package.js:106:12)
    at PackageManager.module.exports.PackageManager.loadPackage (/Users/joel/Downloads/Atom.app/Contents/Resources/app.asar/src/package-manager.js:457:14)
    at /Users/joel/Downloads/Atom.app/Contents/Resources/app.asar/src/package-manager.js:402:19
    at Config.module.exports.Config.transact (/Users/joel/Downloads/Atom.app/Contents/Resources/app.asar/src/config.js:312:16)
    at PackageManager.module.exports.PackageManager.loadPackages (/Users/joel/Downloads/Atom.app/Contents/Resources/app.asar/src/package-manager.js:397:19)
    at /Users/joel/Downloads/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:743:28
```

### Commands

```
```

### Config

```json
{}
```

### Installed Packages

```coffee
# User
language-redprl, v0.0.0

# Dev
No dev packages
```

**Comment by freebroccolo** [comment]
Thanks for the report. I'm not quite sure how the package could have managed to install but then not be able to find one of the required packages. I'll have to try it in a fresh environment and see if I encounter the same issue.

Were there no other errors or warnings or anything during the install? This error occurs as soon as you open Atom?

**Comment by joelburget** [comment]
Fixed by running `apm install` in the cloned dir. Not sure if that's always a necessary step or if it was just something I needed to step through, since the install initially failed with an xcode problem.

**Comment by freebroccolo** [comment]
Yeah, it's a necessary step I forgot to mention 😄  I've updated the steps to mention that.

I also cleaned up a few of the dependencies. If you pull from master and do a fresh install (or just `rm -rf node_modules`) with `apm install --production` it should be faster now. No need to do that if you've already got it working though.
